// smart-function — Supabase Edge Function
// Handles: login, change_password, forgot_password, admin_list_users, admin_create_user, admin_toggle_user

import { serve } from 'https://deno.land/std@0.177.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SUPABASE_SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const ADMIN_USERNAME = 'lidor_admin';
const EMAILJS_SERVICE = 'service_s5wzeck';
const EMAILJS_TEMPLATE_FORGOT = 'template_forgot_password';
const EMAILJS_PUBLIC_KEY = 'ZWYqaiqD2U5oWexSq';

const cors = {
  'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
    };

    function json(body: object, status = 200) {
      return new Response(JSON.stringify(body), {
          status,
              headers: { ...cors, 'Content-Type': 'application/json' },
                });
                }

                function generateTempPassword(): string {
                  const chars = 'ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789';
                    let pass = '';
                      const arr = new Uint8Array(8);
                        crypto.getRandomValues(arr);
                          for (const b of arr) pass += chars[b % chars.length];
                            return pass;
                            }

                            async function hashPassword(password: string): Promise<string> {
                              const encoder = new TextEncoder();
                                const data = encoder.encode(password + 'sl_salt_2024');
                                  const hash = await crypto.subtle.digest('SHA-256', data);
                                    return Array.from(new Uint8Array(hash)).map(b => b.toString(16).padStart(2, '0')).join('');
                                    }

                                    serve(async (req) => {
                                      if (req.method === 'OPTIONS') return new Response('ok', { headers: cors });

                                        let body: Record<string, unknown>;
                                          try { body = await req.json(); } catch { return json({ ok: false, error: 'invalid_json' }, 400); }

                                            const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);
                                              const action = (body.action as string) || 'login';

                                                // ── LOGIN ──────────────────────────────────────────────────────────────────
                                                  if (action === 'login' || !body.action) {
                                                      const { username, passwordHash } = body as { username: string; passwordHash: string };
                                                          if (!username || !passwordHash) return json({ ok: false, error: 'missing_fields' }, 400);

                                                              const { data: users, error } = await supabase
                                                                    .from('users')
                                                                          .select('id, username, email, password_hash, is_active, plan')
                                                                                .eq('username', username)
                                                                                      .limit(1);

                                                                                          if (error) return json({ ok: false, error: 'server_error' }, 500);
                                                                                              if (!users || users.length === 0) return json({ ok: false, error: 'user_not_found' }, 401);

                                                                                                  const user = users[0];
                                                                                                      if (!user.is_active) return json({ ok: false, error: 'account_suspended' }, 403);
                                                                                                          if (user.password_hash !== passwordHash) return json({ ok: false, error: 'wrong_password' }, 401);

                                                                                                              return json({ ok: true, user: { id: user.id, username: user.username, email: user.email, plan: user.plan || 'full' } });
                                                                                                                }

                                                                                                                  // ── CHANGE PASSWORD ────────────────────────────────────────────────────────
                                                                                                                    if (action === 'change_password') {
                                                                                                                        const { username, email, oldHash, newHash } = body as { username: string; email: string; oldHash: string; newHash: string };
                                                                                                                            if (!username || !email || !oldHash || !newHash) return json({ ok: false, error: 'missing_fields' }, 400);

                                                                                                                                const { data: users } = await supabase
                                                                                                                                      .from('users')
                                                                                                                                            .select('id, password_hash, is_active')
                                                                                                                                                  .eq('username', username)
                                                                                                                                                        .eq('email', email)
                                                                                                                                                              .limit(1);

                                                                                                                                                                  if (!users || users.length === 0) return json({ ok: false, error: 'user_not_found' }, 404);
                                                                                                                                                                      const user = users[0];
                                                                                                                                                                          if (!user.is_active) return json({ ok: false, error: 'account_suspended' }, 403);
                                                                                                                                                                              if (user.password_hash !== oldHash) return json({ ok: false, error: 'wrong_password' }, 401);

                                                                                                                                                                                  const { error } = await supabase.from('users').update({ password_hash: newHash }).eq('id', user.id);
                                                                                                                                                                                      if (error) return json({ ok: false, error: 'server_error' }, 500);

                                                                                                                                                                                          return json({ ok: true });
                                                                                                                                                                                            }

                                                                                                                                                                                              // ── FORGOT PASSWORD ────────────────────────────────────────────────────────
                                                                                                                                                                                                if (action === 'forgot_password') {
                                                                                                                                                                                                    const { username } = body as { username: string };
                                                                                                                                                                                                        if (!username) return json({ ok: false, error: 'missing_fields' }, 400);

                                                                                                                                                                                                            const { data: users } = await supabase
                                                                                                                                                                                                                  .from('users')
                                                                                                                                                                                                                        .select('id, email, is_active')
                                                                                                                                                                                                                              .eq('username', username)
                                                                                                                                                                                                                                    .limit(1);

                                                                                                                                                                                                                                        if (!users || users.length === 0) return json({ ok: false, error: 'user_not_found' }, 404);
                                                                                                                                                                                                                                            const user = users[0];
                                                                                                                                                                                                                                                if (!user.is_active) return json({ ok: false, error: 'account_suspended' }, 403);

                                                                                                                                                                                                                                                    const tempPass = generateTempPassword();
                                                                                                                                                                                                                                                        const newHash = await hashPassword(tempPass);

                                                                                                                                                                                                                                                            const { error: updateErr } = await supabase.from('users').update({ password_hash: newHash }).eq('id', user.id);
                                                                                                                                                                                                                                                                if (updateErr) return json({ ok: false, error: 'server_error' }, 500);

                                                                                                                                                                                                                                                                    // Send email via EmailJS REST API
                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                              await fetch('https://api.emailjs.com/api/v1.0/email/send', {
                                                                                                                                                                                                                                                                                      method: 'POST',
                                                                                                                                                                                                                                                                                              headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                      body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                service_id: EMAILJS_SERVICE,
                                                                                                                                                                                                                                                                                                                          template_id: EMAILJS_TEMPLATE_FORGOT,
                                                                                                                                                                                                                                                                                                                                    user_id: EMAILJS_PUBLIC_KEY,
                                                                                                                                                                                                                                                                                                                                              template_params: { to_email: user.email, username, temp_pass: tempPass }
                                                                                                                                                                                                                                                                                                                                                      })
                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                } catch {
                                                                                                                                                                                                                                                                                                                                                                      // Email failed — password was already reset, still return ok
                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                              return json({ ok: true });
                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                  // ── ADMIN: verify helper ───────────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                    async function verifyAdmin(admin_id: string, admin_username: string): Promise<boolean> {
                                                                                                                                                                                                                                                                                                                                                                                        if (admin_username !== ADMIN_USERNAME) return false;
                                                                                                                                                                                                                                                                                                                                                                                            const { data } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                  .from('users')
                                                                                                                                                                                                                                                                                                                                                                                                        .select('id, is_active')
                                                                                                                                                                                                                                                                                                                                                                                                              .eq('id', admin_id)
                                                                                                                                                                                                                                                                                                                                                                                                                    .eq('username', ADMIN_USERNAME)
                                                                                                                                                                                                                                                                                                                                                                                                                          .limit(1);
                                                                                                                                                                                                                                                                                                                                                                                                                              return !!(data && data.length > 0 && data[0].is_active);
                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                  // ── ADMIN: LIST USERS ──────────────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                    if (action === 'admin_list_users') {
                                                                                                                                                                                                                                                                                                                                                                                                                                        const { admin_id, admin_username } = body as { admin_id: string; admin_username: string };
                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!await verifyAdmin(admin_id, admin_username)) return json({ ok: false, error: 'unauthorized' }, 403);

                                                                                                                                                                                                                                                                                                                                                                                                                                                const { data: users, error } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                      .from('users')
                                                                                                                                                                                                                                                                                                                                                                                                                                                            .select('id, username, email, is_active, created_at')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .order('created_at', { ascending: false });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (error) return json({ ok: false, error: 'server_error' }, 500);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return json({ ok: true, users });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // ── ADMIN: CREATE USER ─────────────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (action === 'admin_create_user') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const { admin_id, admin_username, username, email, password_hash } = body as {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          admin_id: string; admin_username: string; username: string; email: string; password_hash: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!await verifyAdmin(admin_id, admin_username)) return json({ ok: false, error: 'unauthorized' }, 403);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!username || !email || !password_hash) return json({ ok: false, error: 'missing_fields' }, 400);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const { error } = await supabase.from('users').insert({ username, email, password_hash, is_active: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (error) return json({ ok: false, error: error.message }, 500);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return json({ ok: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // ── ADMIN: TOGGLE USER ─────────────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (action === 'admin_toggle_user') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const { admin_id, admin_username, target_id, is_active } = body as {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  admin_id: string; admin_username: string; target_id: string; is_active: boolean;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!await verifyAdmin(admin_id, admin_username)) return json({ ok: false, error: 'unauthorized' }, 403);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const { error } = await supabase.from('users').update({ is_active }).eq('id', target_id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (error) return json({ ok: false, error: 'server_error' }, 500);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return json({ ok: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return json({ ok: false, error: 'unknown_action' }, 400);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          